version: '3'

services:

  react-front:
    build: react-front
    volumes:
      - ./react-front:/usr/src/app:delegated
      - /usr/src/app/node_modules
    depends_on:
      - django-back
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    networks:
      - compose-network

  django-back:
    build: django-back
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    env_file:
        - .env
    volumes:
      - ./django-back:/code
      - ./.storage:/storage
    environment:
      DJANGO_DATABASE_HOST: postgres-service
      DJANGO_REDIS_HOST: redis-service
    depends_on:
      - postgres-service
      - redis-service
    networks:
      - compose-network

  celery-worker-back:
      build: django-back
      command: celery -A adventure worker --loglevel=INFO
      ports: []
      env_file:
        - .env
      volumes:
        - ./django-back:/code
        - ./.storage:/storage
      environment:
        DJANGO_DATABASE_HOST: postgres-service
        DJANGO_REDIS_HOST: redis-service
      depends_on:
        - rabbitmq-service
        - postgres-service
        - redis-service
      networks:
        - compose-network

  web:
    image: nginx
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx-web/conf.d:/etc/nginx/conf.d
        - ./.storage:/www
#    depends_on:
#      - django-back
#      - react-front

## -- services --

  postgres-service:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "adventure"
    ports:
      - "5432:5432"
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    networks:
      - compose-network

  rabbitmq-service:
    image: rabbitmq:3.7.0-management-alpine
    ports:
      - "15672:15672"
    networks:
      - compose-network

  redis-service:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - compose-network

networks:
  compose-network:
    driver: bridge
