# Generated by Django 2.0 on 2019-03-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_include_poke_infos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
