# Generated by Django 2.0 on 2019-03-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['-poke_id']},
        ),
        migrations.AddField(
            model_name='pokemon',
            name='img_default',
            field=models.ImageField(upload_to='pokemons/'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='img_shiny',
            field=models.ImageField(upload_to='pokemons/'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='poke_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
